language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.1
    - 7.2
    - hhvm

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

        - php: 5.6
        - php: 7.1
        - php: 7.2

    allow_failures:
        - php: hhvm

before_install:
    - composer selfupdate

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./vendor/bin/phpunit install

after_script:
    - ./vendor/bin/php-coveralls

script:
    - mkdir -p build/logs
    - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml
